---
# tasks file for web

- name: Install Required Package
  package:
    name: python3
    state: present
  become: true
- name: Install Apache Server
  package: 
    name: httpd 
    state: present
  become: true
- name: copy web page from url
  get_url:
    dest: "/var/www/html"
    url: "https://raw.githubusercontent.com/gaurav-gupta-gtm/ansible-aws-automation/master/index.html"
  become: true
- name: Start Apache Service
  service: 
    name: httpd 
    state: started
  become: true

